[phases.setup]
nixpkgs = ["bun"]

buildImage = "ghcr.io/nixpacks/bun:1.2.19"

[phases.install]
cmd = "bun install --frozen-lockfile"

[phases.build]
cmd = "bun run build"

[start]
cmd = "cd apps/server && bun run start"

[variables]
NODE_ENV = "production"

